export interface KeyManBeatList {
    CreatedBy: number,
    DeviceId: string,
    Devicename: string,
    EmailWhoInsert: string,
    EndTime:number,
    End_Lat: number,
    End_Lon: number,
    KmEnd:string,
    KmStart: string,
    MobWhoInsert:string,
    NameWhoInsert: string,
    SectionName: string,
    Start_Lat: number,
    Start_Lon:number,
    UpdatedBy:string,
    UserLoginId: number,
    activeStatus: number,
    beatId:number,
    id: number,
    isApprove: boolean,
    parentId: number,
    startTime: number,
    studentId: number,
  }